language: python
python:
  - "2.7"
before_install:
  - sudo apt-get install python-dbus python-gobject python-gtk2
  - mkdir -p /run/user/$USER/
  - sudo touch /run/user/$USER/bus
install: "pip install -r requirements.txt"
script: nosetests
virtualenv:
    system_site_packages: true
env:
  - DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/$USER/bus
